version: '3'
services:
  auth-services:
    build:
      context: ./Auth-services
    ports:
      - "5050:5050"
    depends_on:
      - postgres

  product-services:
    build:
      context: ./Product-services
    ports:
      - "5051:5051"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc@123456
      MYSQL_DATABASE: booking_db
      MYSQL_USER: root
      MYSQL_PASSWORD: booking_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Abc@123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mysql-data:
  postgres-data: